apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pengeflyt-pdfgen
  namespace: okonomi
  labels:
    team: okonomi
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  image: {{ image }}
  replicas:
    min: 2
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: sokos-oppgjorsrapporter